language: ruby
rvm:
  - "1.9.3"
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database meh_test'
