#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'
cookbook "git"
cookbook "rbenv", git: 'git://github.com/fnichol/chef-rbenv.git'
cookbook 'ruby_build'
cookbook 'mysql'
cookbook 'database'